package com.saveshot;
import android.Manifest;import android.app.*;import android.content.*;import android.content.pm.PackageManager;import android.net.Uri;import android.os.*;import android.provider.MediaStore;import android.widget.*;import androidx.appcompat.app.AppCompatActivity;import androidx.core.app.ActivityCompat;import androidx.core.content.ContextCompat;import com.google.mlkit.vision.common.InputImage;import com.google.mlkit.vision.text.TextRecognition;import com.google.mlkit.vision.text.latin.TextRecognizerOptions;import java.util.*;
public class MainActivity extends AppCompatActivity{
 TextView status,result; boolean watching;
 public void onCreate(Bundle b){super.onCreate(b);setContentView(R.layout.activity_main);status=findViewById(R.id.status);result=findViewById(R.id.result);
 findViewById(R.id.access).setOnClickListener(v->access());findViewById(R.id.watch).setOnClickListener(v->toggle());findViewById(R.id.scan).setOnClickListener(v->scan());
 handle(getIntent());}
 void access(){if(Build.VERSION.SDK_INT>=34)requestPermissions(new String[]{Manifest.permission.READ_MEDIA_IMAGES,Manifest.permission.READ_MEDIA_VISUAL_USER_SELECTED},7);else if(Build.VERSION.SDK_INT>=33)requestPermissions(new String[]{Manifest.permission.READ_MEDIA_IMAGES},7);else requestPermissions(new String[]{Manifest.permission.READ_EXTERNAL_STORAGE},7);}
 boolean allowed(){return ContextCompat.checkSelfPermission(this,Build.VERSION.SDK_INT>=33?Manifest.permission.READ_MEDIA_IMAGES:Manifest.permission.READ_EXTERNAL_STORAGE)==PackageManager.PERMISSION_GRANTED;}
 void toggle(){if(!allowed()){access();return;}watching=!watching;if(watching){startService(new Intent(this,WatchService.class));status.setText("Watcher ON — take a screenshot now.");}else{stopService(new Intent(this,WatchService.class));status.setText("Watcher OFF.");}}
 void scan(){if(!allowed()){access();return;}Intent i=new Intent(this,WatchService.class);i.setAction("SCAN");startService(i);status.setText("Scanning newest screenshot…");}
 protected void onNewIntent(Intent i){super.onNewIntent(i);handle(i);}
 void handle(Intent i){if(i!=null&&Intent.ACTION_SEND.equals(i.getAction())){Uri u=i.getParcelableExtra(Intent.EXTRA_STREAM);if(u!=null)read(u);}}
 void read(Uri u){status.setText("Reading screenshot…");try{InputImage in=InputImage.fromFilePath(this,u);TextRecognition.getClient(TextRecognizerOptions.DEFAULT_OPTIONS).process(in).addOnSuccessListener(t->{String s=t.getText();result.setText(classify(s));status.setText("Done — review the suggestion.");}).addOnFailureListener(e->{result.setText("Could not read this image.");status.setText("OCR failed.");});}catch(Exception e){result.setText("Could not open image.");}}
 String classify(String s){String l=s.toLowerCase(Locale.US);String type="REFERENCE";String action="Review this capture";if(l.matches("(?s).*(apply|submit|send|call|email|book|pay|deadline|due|remind|appointment|interview).*")){type="TASK";action=firstLine(s);}else if(l.matches("(?s).*(recipe|ingredients|calories|protein|cook).*")){type="RECIPE";action="Save recipe / ingredients";}else if(l.matches("(?s).*(price|₹|rs\\.?|inr|\\$|sale|discount|offer|amazon|flipkart).*")){type="SHOPPING";action="Review product or price";}return type+"\\n\\n"+action+"\\n\\n"+s.substring(0,Math.min(600,s.length()));}
 String firstLine(String s){for(String x:s.split("\\R")){String l=x.toLowerCase(Locale.US);if(l.contains("apply")||l.contains("submit")||l.contains("deadline")||l.contains("due")||l.contains("book")||l.contains("send"))return x.trim();}return "Review this task";}
}